#!/usr/bin/python3

from ibapicommon import *
import threading
import time
import datetime
import json
import os
from ibapi.contract import Contract, ContractDetails

def stamp():
	day = datetime.date.fromtimestamp(time.time())
	return day.__str__()

def cache_result(fname, original_callback, callback_args=None, callback_kwargs={}):
		if os.path.exists(fname):
			print('USING CACHED RESULT')
			with open(fname, 'r') as f:
				return json.load(f)
		else:
			print('NO CACHED RESULT AVAILABLE, DOING NEW STUFF')
			data = original_callback(*callback_args, **callback_kwargs)
			with open(fname, 'w') as f:
				json.dump(data, f, indent=3)
			return data

def save(data, fname):
	with open(fname, 'w') as fh:
		json.dump(data, fh, indent=3)

class app_context():
	def __init__(self):
		self.app = IB()
		self.app.connect_portal()
		self.api_thread = threading.Thread(target=run_loop, args=(self.app,), daemon=True)
		self.api_thread.start()
	def __enter__(self):
		return self.app

	def __exit__(self, exc_type, exc_value, exc_tb):
		# cleanup
		print("STOPPING THE APP NOW")
		self.app.disconnect()
def main():
	with app_context() as app:
		print("CONNECTION STATUS: {}".format(app.isConnected()))
		mdata = app.daily_data('META', ndays=400, security_type='STK')
		mdaily = [x['close'] for x in mdata]
		print(json.dumps(volatility_schedule(mdaily), indent=3))

if __name__ == '__main__':
	main()
